---
  - hosts: test-webservers
    become: true
    tasks:
      - name: Install Apache
        yum: name=httpd state=present
        tags: install 

      - name: Enable and Start apache
        service: name=httpd state=started enabled=yes
        tags: start
