---
  - hosts: test-webservers
    vars_files: 
      "../../src/encrypted-secrets/sample-secret-data.yml"
    tasks: 
      - name: "Showing secret data"
        debug: 
          msg: "{{ username }}"
