---
- hosts: localhost
  vars:
    stack_name: "ansible-cloudformation"
    template_path: "./../src/cfn-templates/s3.yml"
  vars_files:
    - "./awskey-vault.yml"
  tasks:
    - name: create EC2 using the cloudformation stack
      cloudformation:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        stack_name: "{{ stack_name }}"
        state: "present"
        disable_rollback: true
        template: "{{ template_path }}"
      tags:
        - Stack: "ansible-cloudformation"
