---
- hosts: localhost
  vars:
      instance_type: "t2.micro"
      ec2_name_tag_value: "TestInstance"
      new_ec2_tag_value: "NewTestInstance"
  vars_files: 
      - "./awskey-vault.yml"
  tasks:
    - name: "Finding instance matching with tags"
      ec2_instance_facts: 
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       ec2_region: "{{ AWS_REGION }}"
       filters: 
         tag:Name: "{{ ec2_name_tag_value }}"
      register: ec2_facts

    - name: "Print Info Debugging"
      debug:
        msg: 
          "{{ item.security_groups[0].group_id }} {{ ec2_facts.instances[0].image_id }}"
      loop: "{{ ec2_facts.instances }}"

    - name: "Create New EC2 instance based on the facts"
      ec2: 
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       ec2_region: "{{ AWS_REGION }}"
       instance_type: "{{ instance_type }}"
       image: "{{ ec2_facts.instances[0].image_id }}"
       assign_public_ip: yes
       vpc_subnet_id: "{{ ec2_facts.instances[0].subnet_id }}"
       group_id: "{{ ec2_facts.instances[0].security_groups[0].group_id }}"
       instance_tags:
         Name: "{{ new_ec2_tag_value }}" 
