---
- hosts: localhost
  vars:
      ec2_name_tag_value: "TestInstance"
  vars_files: 
      - "./awskey-vault.yml"
  tasks:
    - name: "Finding instance matching with tags"
      ec2_instance_facts: 
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       ec2_region: "{{ AWS_REGION }}"
       filters: 
         tag:Name: "{{ ec2_name_tag_value }}"
      register: ec2_facts

    - name: "Print Instance Id for Deebugging"
      debug:
        msg: "{{ item.instance_id }}"
      loop: "{{ ec2_facts.instances }}"

    - name: "Get Ec2 id from facts and terminate EC2 instance."
      ec2: 
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       ec2_region: "{{ AWS_REGION }}"
       instance_id: "{{ item.instance_id }}"
       state: absent
      loop: "{{ ec2_facts.instances }}"
