---
  - hosts: localhost
    vars:
      instance_type: "t2.micro"
      image_id: "ami-0ab4xxx" 
      subnet: "subnet-044xxx"
      ec2_name_tag_value: "TestInstance"
      keypair: "mykey-sandbox"
      sg: "sg-0d53xx"
      inventory_group: "autoscalegroup"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "Launching EC2 instance"
        ec2: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          instance_type: "{{ instance_type }}"
          image: "{{ image_id }}"
          assign_public_ip: yes
          vpc_subnet_id: "{{ subnet }}"
          group_id: "{{ sg }}"
          keypair: "{{ keypair }}"
          wait: true
          exact_count: 1
          count_tag: 
            Name: "{{ ec2_name_tag_value }}"
          instance_tags:
            Name: "{{ ec2_name_tag_value }}"
        register: ec2

      - debug: 
          msg: "{{ item.public_ip }}"
        loop: "{{ ec2.instances }}"

      - name: "Adding new host to inventory group"
        add_host: 
          hostname: "{{ item.private_ip }}"
          groupname: "{{ inventory_group }}"
          ansible_ssh_common_args: "ssh -o StrictHostKeyChecking=no"
          ansible_ssh_private_key_file: "~/.ssh/ansible.pem"
        loop: "{{ ec2.instances }}"
        register: add_host

      - debug:
         msg: "{{ add_host }}"  

  - hosts: autoscalegroup
    gather_facts: no
    remote_user: ec2-user
    tasks:
      - name: "Wait for SSH"
        wait_for_connection: 
          delay: 5
          timeout: 90
      - name: "Check host"
        shell: hostname
