---
  - hosts: localhost
    vars:
      vpc_id: "vpc-05e16bb216e75e759"
      report_file: "/home/ec2-user/report.txt"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "VPC info"
        ec2_vpc_net_info: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          #vpc_ids: "{{ vpc_id }}"
          filters:
            vpc-id: "{{ vpc_id }}"
        register: vpc_info
      - name: "Add VPC info to file"
        lineinfile:
          path: "{{ report_file }}"
          line: "VPC ID: {{ vpc_info.vpcs[0].tags.Name }}  =>  {{ vpc_info.vpcs[0].id }}"
          create: yes

      - name: "Subnet Info"
        ec2_vpc_subnet_info:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          filters:
            vpc-id: "{{ vpc_id }}"
        register: subnet_info

      - name: "Add Subnet info to file"
        lineinfile:
          path: "{{ report_file }}"
          line: "Subnet ID: {{ item.subnet_id }} {{ item.tags.Name }} {{ item.cidr_block }}"
        loop_control:
          label: "{{ item.subnet_id }}"
        loop: "{{ subnet_info.subnets }}"
        when: subnet_info.subnets != []

      - name: "Security Group Info"
        ec2_group_info:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          filters:
            vpc-id: "{{ vpc_id }}"
        register: sg_info

      - name: "Add Security group info"
        lineinfile:
          path: "{{ report_file }}"
          line: "Security Group: {{ item.group_name }}  =>  {{ item.description }} => {{ item.ip_permissions }}"  
        loop_control:
          label: "{{ item.group_id }}"
        loop: "{{ sg_info.security_groups }}"
        when: sg_info.security_groups != []

      - name: "Route Info"
        ec2_vpc_route_table_info:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          filters:
            vpc-id: "{{ vpc_id }}"
        register: route_info

      - name: "Print Security info"
        lineinfile:
          path: "{{ report_file }}"
          line: "Route Id: {{ item.id }}"
        loop_control:
          label: "{{ item.route_table_id }}"
        loop: "{{ route_info.route_tables }}"
        when: route_info.route_tables != []
