---
  - hosts: appservers
    become: true
    vars: 
      path_to_app: "/var/www/html" 

    tasks:
      - name: App server info
        copy: 
          dest: "{{ path_to_app }}/info.html"
          content: "{{ ansible_system }} - {{ ansible_hostname }}"
        tags: refresh_info

      - name: File Copy
        copy: src=../../src/my-app/index.html dest="{{ path_to_app }}/index.html" mode=0644
        notify: Reload Apache
        tags: update_index

      - name: List content from directory
        command: "ls -lta {{ path_to_app }}"
        register: html_dir_content

      - name: Show directory content
        debug:
          msg: "{{ html_dir_content }}"
    
    handlers:
      - name: Reload Apache
        service: name=httpd state=reloaded
