---
- hosts: localhost
  vars:
    stack_name: "ansible-cloudformation"
  vars_files:
    - "./awskey-vault.yml"
  tasks:
    - name: cloudformation info
      cloudformation_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        stack_name: "{{ stack_name }}"
      register: cfn_info

    - debug:
        msg: "{{ cfn_info }}"
