---
  - hosts: localhost
    vars:
      volume_name: "test_volume"
      availability_zone: "us-east-1a"
      volume_type: "gp2"
      volume_size: "10" 
      device_name: "/dev/xvdf1"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "Create EBS volume"
        ec2_vol: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          name: "{{ volume_name }}"
          zone: "{{  availability_zone }}"
          volume_type: "{{ volume_type }}"
          volume_size: "{{ volume_size }}"
          device_name: "{{ device_name }}"
        register: vol_info
      - debug: 
          var: vol_info
