---
  - hosts: localhost
    vars: 
      ec2_resource: "i-0d14fb3c0a6f275b6" 
      project_name: "TestProject"
      team_name: "TestTeam"
    vars_files: 
      - "./awskey-vault.yml"
    tasks: 
      - name: "Adding tags"
        ec2_tag:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          resource: "{{ ec2_resource }}"
          state: present
          tags: 
            project: "{{ project_name }}" 
            team: "{{ team_name }}"
