---
  - hosts: localhost
    vars: 
      ec2_name_tag_value: "TestInstance" 
    vars_files: 
      - "./awskey-vault.yml"
    tasks: 
      - name: Stop instance based on instance tag
        ec2:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          state: stopped
          instance_tags: 
            Name: "{{ ec2_name_tag_value }}"
        tags: stop

      - name: Start instance based on instance tag
        ec2:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          state: running
          instance_tags:
            Name: "{{ ec2_name_tag_value }}"
        tags: start
