---
  - hosts: localhost
    vars: 
      ec2_id: "i-03192c8dac84c41b8" 
    vars_files: 
      - "./awskey-vault.yml"
    tasks: 
      - name: Removing tag
        ec2_tag:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          resource: "{{ ec2_id }}"
          state: absent
          tags: 
            Name:
