---
- hosts: localhost
  vars:
      ami_id: "ami-02f9fe1188914a30e"
  vars_files: 
      - "./awskey-vault.yml"

  tasks:
    - name: "Remove ami"
      ec2_ami:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        image_id: "{{ ami_id }}"
        state: absent
        wait: yes
