---
- hosts: localhost
  vars:
      ec2_id: "i-0ce39466a0e0feb19"
  vars_files: 
      - "./awskey-vault.yml"
  tasks:
    - name: "Terminating EC2 instance based on Id.Cannot do directly with tags."
      ec2: 
       aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
       aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
       ec2_region: "{{ AWS_REGION }}"
       instance_id: "{{ ec2_id }}"
       state: absent
