---
  - hosts: localhost
    vars:
      user: "test-user"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "Create IAM user"
        iam: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          iam_type: user
          state: present
          name: "{{ user }}"
          password: "{{ USER_PASS }}"
