---
  - hosts: localhost
    vars:
      group: "test-group"
      user: "test-user"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "Create IAM user"
        iam_group: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          state: present
          name: "{{ group }}"
          managed_policy: 
            - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
          users: 
            - "{{ user }}"
