---
  - hosts: localhost
    vars:
      vpc_id: "vpc-05e16bb216e75e759"
    vars_files: 
      - "./awskey-vault.yml"
    tasks:
      - name: "Launching EC2 instance"
        ec2_vpc_net_info: 
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
          #vpc_ids: "{{ vpc_id }}"
          filters:
            vpc-id: "{{ vpc_id }}"
        register: vpc_info 
      - debug:
          var: vpc_info
